const questions = [
  {q:"Hoạt động nào có thể vi phạm đạo đức, pháp luật số?",a:["Soạn đơn xin việc","Vẽ biểu đồ","Viết bình luận xúc phạm người khác","Tính toán"],c:2},
  {q:"Trang web nào đáng tin cậy nhất?",a:["Trang .gov.vn","Trang nhiều quảng cáo","Trang giật gân","Trang không rõ nguồn"],c:0},
  {q:"Hành động nào KHÔNG vi phạm đạo đức số?",a:["Sao chép bài người khác","Xâm nhập tài khoản","Chia sẻ thông tin sai","Tôn trọng bản quyền"],c:3},
  {q:"Thiết bị nào là thiết bị nhập?",a:["Màn hình","Máy in","Bàn phím","Loa"],c:2},
  {q:"Thiết bị nào là thiết bị xuất?",a:["Chuột","Bàn phím","Màn hình","Webcam"],c:2},
  {q:"Phần mềm nào sau đây là hệ điều hành?",a:["Word","Windows","Chrome","Excel"],c:1},
  {q:"Máy tính dùng để làm gì?",a:["Nghe gọi","Xử lý thông tin","Nấu ăn","Chụp ảnh"],c:1},
  {q:"Đơn vị đo dung lượng nhỏ nhất?",a:["GB","MB","KB","Byte"],c:3},
  {q:"Phần cứng là gì?",a:["Chương trình","Dữ liệu","Thiết bị vật lý","Mạng Internet"],c:2},
  {q:"Thiết bị lưu trữ?",a:["CPU","RAM","Ổ cứng","Màn hình"],c:2},

  {q:"Phần mềm bảng tính là?",a:["Word","Excel","PowerPoint","Paint"],c:1},
  {q:"Ô trong bảng tính được xác định bởi?",a:["Tên","Màu","Cột và hàng","Kích thước"],c:2},
  {q:"Địa chỉ ô A1 là?",a:["Cột A hàng 1","Hàng A cột 1","Cột 1 hàng A","Sai"],c:0},
  {q:"Công thức trong Excel bắt đầu bằng?",a:["@","=","#","+"],c:1},
  {q:"Hàm SUM dùng để?",a:["Đếm","Cộng","Nhân","Chia"],c:1},
  {q:"Hàm AVERAGE dùng để?",a:["Cộng","Trung bình","Đếm","So sánh"],c:1},
  {q:"Hàm COUNT dùng để?",a:["Đếm số","Cộng","Lớn nhất","Nhỏ nhất"],c:0},
  {q:"Hàm MAX dùng để?",a:["Lớn nhất","Nhỏ nhất","Trung bình","Đếm"],c:0},
  {q:"Hàm MIN dùng để?",a:["Nhỏ nhất","Lớn nhất","Cộng","Đếm"],c:0},
  {q:"Muốn sao chép công thức ta dùng?",a:["Chuột phải","Fill Handle","Menu","Delete"],c:1},

  {q:"Sắp xếp dữ liệu dùng để?",a:["Xóa","In","Thay đổi thứ tự","Vẽ"],c:2},
  {q:"Lọc dữ liệu dùng để?",a:["Ẩn bớt dữ liệu","Xóa","Sửa","Sao chép"],c:0},
  {q:"Biểu đồ dùng để?",a:["Trang trí","Xử lý","So sánh","Lưu trữ"],c:2},
  {q:"Biểu đồ cột dùng để?",a:["So sánh","Tính","In","Xóa"],c:0},
  {q:"Biểu đồ tròn dùng để?",a:["So sánh","Thể hiện tỉ lệ","Đếm","Lọc"],c:1},
  {q:"Biểu đồ đường dùng để?",a:["Theo dõi thay đổi","Tính","In","Lọc"],c:0},

  {q:"Phần mềm soạn thảo văn bản?",a:["Excel","Paint","Word","Chrome"],c:2},
  {q:"Chức năng căn lề dùng để?",a:["Đổi màu","Canh chữ","Chèn ảnh","Lưu"],c:1},
  {q:"Chức năng in văn bản?",a:["Print","Save","Open","Close"],c:0},
  {q:"Định dạng chữ gồm?",a:["Màu, cỡ, kiểu","Số","Hàm","Biểu đồ"],c:0},
  {q:"Gạch chân chữ là?",a:["Bold","Italic","Underline","Align"],c:2},
  {q:"In đậm chữ là?",a:["Bold","Italic","Underline","Align"],c:0},
  {q:"In nghiêng chữ là?",a:["Bold","Italic","Underline","Align"],c:1},

  {q:"Internet dùng để?",a:["Chơi","Học tập","Trao đổi thông tin","Tất cả đều đúng"],c:3},
  {q:"Email dùng để?",a:["Chơi game","Gửi thư điện tử","Soạn văn bản","Tính toán"],c:1},
  {q:"Trang tìm kiếm phổ biến?",a:["Facebook","Google","Word","Excel"],c:1},
  {q:"Mạng xã hội dùng để?",a:["Kết nối","In","Lưu","Tính"],c:0},
  {q:"Hành vi đúng khi dùng Internet?",a:["Nói xấu","Tôn trọng người khác","Chia sẻ tin giả","Vi phạm bản quyền"],c:1},
  {q:"Virus máy tính gây?",a:["Tăng tốc","Lỗi máy","Trang trí","In nhanh"],c:1},
  {q:"Phần mềm diệt virus dùng để?",a:["Tạo virus","Xóa virus","Chia sẻ","Trang trí"],c:1},

  {q:"An toàn thông tin là?",a:["Giữ bí mật","Chia sẻ","Xóa","Sao chép"],c:0},
  {q:"Mật khẩu mạnh cần?",a:["Dễ nhớ","Ngắn","Kết hợp ký tự","Chỉ số"],c:2},
  {q:"Không nên chia sẻ?",a:["Tên","Tuổi","Mật khẩu","Sở thích"],c:2},
  {q:"Hành vi đúng?",a:["Xâm nhập","Tôn trọng riêng tư","Hack","Lừa đảo"],c:1},
  {q:"Sử dụng CNTT có trách nhiệm là?",a:["Vi phạm","Tôn trọng luật","Gây hại","Sao chép"],c:1},
  {q:"Tin học giúp?",a:["Học tập hiệu quả","Mất thời gian","Hại sức khỏe","Không lợi"],c:0}
];
